#!/bin/bash

# =====================================================
# CBT Recording Setup Script
# =====================================================
# Purpose: Apply optimized PHP and Nginx configurations for 1GB video upload
# Usage: sudo bash setup-cbt-recording.sh

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Configuration
APP_DIR="/var/www/html/procbt_id"
CONFIG_DIR="$APP_DIR/config"
PHP_VERSION="8.3"
NGINX_USER="www-data"

echo -e "${BLUE}=====================================================${NC}"
echo -e "${BLUE}    CBT Recording Configuration Setup Script${NC}"
echo -e "${BLUE}=====================================================${NC}"

# =====================================================
# FUNCTION DEFINITIONS
# =====================================================

log_info() {
    echo -e "${GREEN}[INFO]${NC} $1"
}

log_warn() {
    echo -e "${YELLOW}[WARN]${NC} $1"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

check_root() {
    if [[ $EUID -ne 0 ]]; then
        log_error "This script must be run as root (use sudo)"
        exit 1
    fi
}

backup_config() {
    local config_file="$1"
    local backup_file="${config_file}.backup.$(date +%Y%m%d_%H%M%S)"

    if [[ -f "$config_file" ]]; then
        cp "$config_file" "$backup_file"
        log_info "Backed up $config_file to $backup_file"
    fi
}

# =====================================================
# MAIN SETUP FUNCTIONS
# =====================================================

setup_directories() {
    log_info "Setting up directories..."

    # Create required directories
    mkdir -p /var/log/php
    mkdir -p /var/cache/nginx/client_temp
    mkdir -p /var/cache/nginx/proxy_temp
    mkdir -p /var/cache/nginx/fastcgi_temp
    mkdir -p "$APP_DIR/storage/tmp"
    mkdir -p "$APP_DIR/storage/app/recordings"

    # Set proper permissions
    chown -R $NGINX_USER:$NGINX_USER /var/cache/nginx/
    local cli_user="${SUDO_USER:-procbt}"
    chown -R $cli_user:www-data "$APP_DIR/storage/"
    chmod -R 775 "$APP_DIR/storage/"

    log_info "Directories created and permissions set"
}

setup_php() {
    log_info "Configuring PHP for large video uploads..."

    # Backup current php.ini
    backup_config "/etc/php/$PHP_VERSION/fpm/php.ini"

    # Apply PHP configuration
    cat > "/etc/php/$PHP_VERSION/fpm/conf.d/99-z-cbt-recording.ini" << EOF
; CBT Recording Configuration
; Auto-generated by setup script

; Upload settings
upload_max_filesize = 1200M
post_max_size = 1300M
max_file_uploads = 20

; Memory and execution
memory_limit = 2048M
max_execution_time = 1800
max_input_time = 1200
max_input_vars = 5000

; Session settings
session.gc_maxlifetime = 7200
session.cookie_lifetime = 7200

; Temporary directories
upload_tmp_dir = $APP_DIR/storage/tmp
sys_temp_dir = $APP_DIR/storage/tmp

; Error logging
log_errors = On
error_log = /var/log/php/cbt-recording-errors.log
display_errors = Off

; Performance
output_buffering = 4096
opcache.enable = 1
opcache.memory_consumption = 256
opcache.max_accelerated_files = 20000

; Timezone
date.timezone = "Asia/Jakarta"

; Compression
zlib.output_compression = On
zlib.output_compression_level = 6
EOF

    # Also apply to CLI (for artisan commands)
    cp "/etc/php/$PHP_VERSION/fpm/conf.d/99-z-cbt-recording.ini" "/etc/php/$PHP_VERSION/cli/conf.d/"

    log_info "PHP configuration applied"
}

setup_php_fpm() {
    log_info "Configuring PHP-FPM for better performance..."

    # Backup current pool configuration
    backup_config "/etc/php/$PHP_VERSION/fpm/pool.d/www.conf"

    # Apply PHP-FPM pool configuration
    cat > "/etc/php/$PHP_VERSION/fpm/pool.d/cbt-recording.conf" << EOF
; CBT Recording PHP-FPM Pool Configuration

[cbt-recording]
user = $NGINX_USER
group = $NGINX_USER
listen = /var/run/php/php$PHP_VERSION-fpm-cbt.sock
listen.owner = $NGINX_USER
listen.group = $NGINX_USER
listen.mode = 0660

; Process management
pm = dynamic
pm.max_children = 50
pm.start_servers = 5
pm.min_spare_servers = 5
pm.max_spare_servers = 35
pm.max_requests = 1000

; Request timeouts
request_terminate_timeout = 1800s
request_slowlog_timeout = 30s
slowlog = /var/log/php/cbt-recording-slow.log

; Environment variables
env[HOSTNAME] = \$HOSTNAME
env[PATH] = /usr/local/bin:/usr/bin:/bin
env[TMP] = $APP_DIR/storage/tmp
env[TMPDIR] = $APP_DIR/storage/tmp
env[TEMP] = $APP_DIR/storage/tmp

; Security
security.limit_extensions = .php .phtml

; Access log
access.log = /var/log/php/cbt-recording-access.log
access.format = "%R - %u %t \"%m %r%Q%q\" %s %f %{mili}d %{kilo}M %C%%"
EOF

    log_info "PHP-FPM pool configuration applied"
}

setup_nginx() {
    log_info "Configuring Nginx for large video uploads..."

    # Backup current nginx configuration
    backup_config "/etc/nginx/nginx.conf"

    # Create CBT-specific configuration
    cat > "/etc/nginx/conf.d/cbt-recording.conf" << EOF
# CBT Recording Nginx Configuration

# Large upload settings
# client_max_body_size 1500M; # (Defined in site server blocks)
client_body_timeout 600s;
client_header_timeout 60s;
# client_body_buffer_size 128k; # (Defined in nginx.conf)

# Send timeout
send_timeout 600s;

# Keepalive settings
# keepalive_timeout 300s; # (Defined in nginx.conf)
# keepalive_requests 1000; # (Defined in nginx.conf)

# FastCGI settings
fastcgi_connect_timeout 60s;
fastcgi_send_timeout 600s;
fastcgi_read_timeout 600s;
fastcgi_buffers 16 16k;
fastcgi_buffer_size 32k;
fastcgi_busy_buffers_size 64k;

# Proxy settings
proxy_connect_timeout 60s;
proxy_send_timeout 600s;
proxy_read_timeout 600s;
proxy_buffers 8 16k;
proxy_buffer_size 32k;

# Temporary paths
client_body_temp_path /var/cache/nginx/client_temp;
proxy_temp_path /var/cache/nginx/proxy_temp;
fastcgi_temp_path /var/cache/nginx/fastcgi_temp;

# Rate limiting
limit_req_zone \$binary_remote_addr zone=upload:10m rate=10r/m;
limit_req_zone \$binary_remote_addr zone=api:10m rate=100r/m;
EOF

    log_info "Nginx configuration applied"
}

optimize_system() {
    log_info "Optimizing system for video processing..."

    # Increase file descriptor limits
    cat > "/etc/security/limits.d/cbt-recording.conf" << EOF
# CBT Recording - File descriptor limits
$NGINX_USER soft nofile 65536
$NGINX_USER hard nofile 65536
root soft nofile 65536
root hard nofile 65536
EOF

    # Optimize kernel parameters
    cat > "/etc/sysctl.d/99-cbt-recording.conf" << EOF
# CBT Recording - Kernel optimizations

# Network optimizations
net.core.rmem_default = 262144
net.core.rmem_max = 16777216
net.core.wmem_default = 262144
net.core.wmem_max = 16777216

# File system optimizations
fs.file-max = 2097152
fs.inotify.max_user_watches = 524288

# Virtual memory optimizations
vm.swappiness = 10
vm.dirty_ratio = 15
vm.dirty_background_ratio = 5
EOF

    sysctl -p /etc/sysctl.d/99-cbt-recording.conf

    log_info "System optimizations applied"
}

restart_services() {
    log_info "Restarting services..."

    # Test configurations first
    nginx -t
    php-fpm$PHP_VERSION -t

    # Restart services
    systemctl restart php$PHP_VERSION-fpm
    systemctl restart nginx

    # Enable services
    systemctl enable php$PHP_VERSION-fpm
    systemctl enable nginx

    log_info "Services restarted successfully"
}

verify_setup() {
    log_info "Verifying setup..."

    # Check service status
    if systemctl is-active --quiet nginx; then
        log_info "✓ Nginx is running"
    else
        log_error "✗ Nginx is not running"
    fi

    if systemctl is-active --quiet php$PHP_VERSION-fpm; then
        log_info "✓ PHP-FPM is running"
    else
        log_error "✗ PHP-FPM is not running"
    fi

    # Check PHP configuration
    PHP_UPLOAD_MAX=$(php -r "echo ini_get('upload_max_filesize');")
    PHP_POST_MAX=$(php -r "echo ini_get('post_max_size');")
    PHP_MEMORY=$(php -r "echo ini_get('memory_limit');")

    log_info "PHP Configuration:"
    log_info "  - Upload max: $PHP_UPLOAD_MAX"
    log_info "  - Post max: $PHP_POST_MAX"
    log_info "  - Memory limit: $PHP_MEMORY"

    # Check disk space
    DISK_USAGE=$(df -h "$APP_DIR" | awk 'NR==2 {print $4}')
    log_info "Available disk space: $DISK_USAGE"

    # Performance test endpoint
    log_info "Setup verification complete!"
}

# =====================================================
# MAIN EXECUTION
# =====================================================

main() {
    check_root

    log_info "Starting CBT Recording setup..."
    log_info "App directory: $APP_DIR"
    log_info "PHP version: $PHP_VERSION"

    setup_directories
    setup_php
    setup_php_fpm
    setup_nginx
    optimize_system
    restart_services
    verify_setup

    echo -e "${GREEN}=====================================================${NC}"
    echo -e "${GREEN}    CBT Recording Setup Complete!${NC}"
    echo -e "${GREEN}=====================================================${NC}"
    echo -e "${GREEN}✓ PHP configured for 1GB+ uploads${NC}"
    echo -e "${GREEN}✓ Nginx optimized for large files${NC}"
    echo -e "${GREEN}✓ System optimizations applied${NC}"
    echo -e "${GREEN}✓ Services restarted and enabled${NC}"
    echo -e ""
    echo -e "${YELLOW}Next steps:${NC}"
    echo -e "1. Test upload functionality with large files"
    echo -e "2. Monitor logs: /var/log/php/ and /var/log/nginx/"
    echo -e "3. Use the monitoring script: bash monitor-cbt-performance.sh"
    echo -e ""
    echo -e "${BLUE}Configuration files created:${NC}"
    echo -e "- /etc/php/$PHP_VERSION/fpm/conf.d/99-z-cbt-recording.ini"
    echo -e "- /etc/php/$PHP_VERSION/fpm/pool.d/cbt-recording.conf"
    echo -e "- /etc/nginx/conf.d/cbt-recording.conf"
    echo -e "- /etc/security/limits.d/cbt-recording.conf"
    echo -e "- /etc/sysctl.d/99-cbt-recording.conf"
}

# Run main function
main "$@"
